// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTMwErSB1cL4xXDa0_YapqwFv63MAHRc',
    appId: '1:838743198796:android:2cfa3b92d3c0241eb6b8e9',
    messagingSenderId: '838743198796',
    projectId: 'abap-aed31',
    storageBucket: 'abap-aed31.firebasestorage.app',
  );

  /// iOS is not configured, and must fail loudly rather than half-run.
  ///
  /// This used to return a FirebaseOptions full of `YOUR_IOS_API_KEY`
  /// placeholders under a bundle id inherited from the upstream template this
  /// repo was forked from, which does not exist in project abap-aed31 (the one
  /// the Android options above use). `Firebase.initializeApp` would reject them,
  /// main.dart would catch and carry on, and the app would come up with
  /// sign-in, Remote Config, purchases (the iOS RevenueCat key is a
  /// placeholder too) and real ad revenue all quietly dead — with no symptom
  /// beyond "nothing works".
  ///
  /// Throwing matches how every other unconfigured platform above behaves, and
  /// turns "shipped iOS by accident" into a crash on the first line instead of
  /// a support thread. Restore real values here, and set
  /// `revenuecat.apiKey.ios` plus the two `ads.*.adUnitId.ios` Remote Config
  /// defaults, when `flutter create --platforms=ios .` regenerates the iOS
  /// project — ios/ currently has no Runner.xcodeproj at all.
  static FirebaseOptions get ios => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for iOS - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
}
